# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', tinymce.models.HTMLField(verbose_name='文章内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'verbose_name_plural': '我的文章',
                'verbose_name': '我的文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(1, 'Python基础'), (2, '数据库'), (3, 'Django'), (4, '碎言碎语'), (5, '源码分享'), (6, '学无止境')], verbose_name='文章分类')),
            ],
            options={
                'verbose_name_plural': '文章分类',
                'verbose_name': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='文章类别'),
        ),
    ]
