# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='description',
            field=models.CharField(default=None, max_length=120, null=True, verbose_name='文章描述'),
        ),
    ]
