# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_tagsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='文章分类'),
        ),
    ]
